# Generated by Django 4.2.23 on 2025-08-23 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customer_user_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderline',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.customer'),
        ),
    ]
