# Generated by Django 5.2.5 on 2025-09-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderline_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='', upload_to='food_images/'),
            preserve_default=False,
        ),
    ]
